version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(deps): '

  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    groups:
      frontend:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: [ 'version-update:semver-major' ]
